version: "3.8"
services:
  db:
    image: postgres:12
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 127.0.0.1:${LOCAL_DB_PORT}:5432
    # restart: always

  app:
    build: .
    # restart: always
    ports:
      - 127.0.0.1:${APP_LOCAL_PORT}:5000
    # depends_on:
    #   - db
    # volumes:
    # - ./:/app
    environment:
      - FLASK_APP=run:app
      - FLASK_ENV=production
      - FLASK_DEBUG=0

volumes:
  db_data:
