version: "3.8"
services:
  app:
    build: .
    # restart: always
    ports:
      - 127.0.0.1:${APP_LOCAL_PORT}:5000
    volumes:
      - ./db:./db
    environment:
      - FLASK_APP=run:app
      - FLASK_ENV=production
      - FLASK_DEBUG=0

volumes:
  db_data:
